# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'middles_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.is_middle_button = QtWidgets.QPushButton(self.groupBox)
        self.is_middle_button.setStyleSheet("font: 18pt \"Sans Serif\";")
        self.is_middle_button.setObjectName("is_middle_button")
        self.horizontalLayout_4.addWidget(self.is_middle_button)
        self.is_not_middle_button = QtWidgets.QPushButton(self.groupBox)
        self.is_not_middle_button.setStyleSheet("font: 18pt \"Sans Serif\";")
        self.is_not_middle_button.setObjectName("is_not_middle_button")
        self.horizontalLayout_4.addWidget(self.is_not_middle_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.status_label = QtWidgets.QLabel(self.groupBox)
        self.status_label.setObjectName("status_label")
        self.verticalLayout_2.addWidget(self.status_label)
        self.middle_text_viewer = QtWidgets.QTextBrowser(self.groupBox)
        self.middle_text_viewer.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.middle_text_viewer.setObjectName("middle_text_viewer")
        self.verticalLayout_2.addWidget(self.middle_text_viewer)
        self.note_editor = QtWidgets.QPlainTextEdit(self.groupBox)
        self.note_editor.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.note_editor.setObjectName("note_editor")
        self.verticalLayout_2.addWidget(self.note_editor)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.which_middle_spin_box = QtWidgets.QSpinBox(self.groupBox)
        self.which_middle_spin_box.setObjectName("which_middle_spin_box")
        self.horizontalLayout_3.addWidget(self.which_middle_spin_box)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.add_middle_button = QtWidgets.QPushButton(self.groupBox)
        self.add_middle_button.setObjectName("add_middle_button")
        self.horizontalLayout_2.addWidget(self.add_middle_button)
        self.remove_middle_button = QtWidgets.QPushButton(self.groupBox)
        self.remove_middle_button.setIconSize(QtCore.QSize(16, 16))
        self.remove_middle_button.setObjectName("remove_middle_button")
        self.horizontalLayout_2.addWidget(self.remove_middle_button)
        self.reset_entry_button = QtWidgets.QPushButton(self.groupBox)
        self.reset_entry_button.setMinimumSize(QtCore.QSize(0, 23))
        self.reset_entry_button.setObjectName("reset_entry_button")
        self.horizontalLayout_2.addWidget(self.reset_entry_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.subject_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.subject_line_edit.setObjectName("subject_line_edit")
        self.gridLayout.addWidget(self.subject_line_edit, 0, 1, 1, 1)
        self.subject_spin_box = QtWidgets.QSpinBox(self.groupBox)
        self.subject_spin_box.setObjectName("subject_spin_box")
        self.gridLayout.addWidget(self.subject_spin_box, 0, 2, 1, 1)
        self.verb_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.verb_line_edit.setObjectName("verb_line_edit")
        self.gridLayout.addWidget(self.verb_line_edit, 1, 1, 1, 1)
        self.adverb_line_edit = QtWidgets.QLineEdit(self.groupBox)
        self.adverb_line_edit.setObjectName("adverb_line_edit")
        self.gridLayout.addWidget(self.adverb_line_edit, 2, 1, 1, 1)
        self.verb_spin_box = QtWidgets.QSpinBox(self.groupBox)
        self.verb_spin_box.setObjectName("verb_spin_box")
        self.gridLayout.addWidget(self.verb_spin_box, 1, 2, 1, 1)
        self.adverb_spin_box = QtWidgets.QSpinBox(self.groupBox)
        self.adverb_spin_box.setObjectName("adverb_spin_box")
        self.gridLayout.addWidget(self.adverb_spin_box, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.next_button = QtWidgets.QPushButton(self.groupBox)
        self.next_button.setStyleSheet("font: 18pt \"Sans Serif\";")
        self.next_button.setIconSize(QtCore.QSize(16, 20))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.previous_button = QtWidgets.QPushButton(self.groupBox)
        self.previous_button.setStyleSheet("font: 18pt \"Sans Serif\";")
        self.previous_button.setIconSize(QtCore.QSize(16, 20))
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout.addWidget(self.previous_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 20))
        self.menubar.setObjectName("menubar")
        self.menuControls = QtWidgets.QMenu(self.menubar)
        self.menuControls.setObjectName("menuControls")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_and_Exit = QtWidgets.QAction(MainWindow)
        self.actionSave_and_Exit.setObjectName("actionSave_and_Exit")
        self.actionGo_to_next_Unaccounted = QtWidgets.QAction(MainWindow)
        self.actionGo_to_next_Unaccounted.setObjectName("actionGo_to_next_Unaccounted")
        self.menuControls.addAction(self.actionSave_and_Exit)
        self.menuControls.addAction(self.actionGo_to_next_Unaccounted)
        self.menubar.addAction(self.menuControls.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Middle x/y"))
        self.is_middle_button.setText(_translate("MainWindow", "Is a Middle"))
        self.is_not_middle_button.setText(_translate("MainWindow", "Is not a Middle"))
        self.status_label.setText(_translate("MainWindow", "Status"))
        self.middle_text_viewer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">this middle reads well</span></p></body></html>"))
        self.note_editor.setPlainText(_translate("MainWindow", "this is a good note"))
        self.label_4.setText(_translate("MainWindow", "Which Middle:"))
        self.add_middle_button.setText(_translate("MainWindow", "Add Middle"))
        self.remove_middle_button.setText(_translate("MainWindow", "Remove Middle"))
        self.reset_entry_button.setText(_translate("MainWindow", "Reset Entry"))
        self.label.setText(_translate("MainWindow", "Subject"))
        self.label_2.setText(_translate("MainWindow", "Verb"))
        self.label_3.setText(_translate("MainWindow", "Adverb"))
        self.subject_line_edit.setText(_translate("MainWindow", "middle"))
        self.verb_line_edit.setText(_translate("MainWindow", "reads"))
        self.adverb_line_edit.setText(_translate("MainWindow", "well"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.menuControls.setTitle(_translate("MainWindow", "Controls"))
        self.actionSave_and_Exit.setText(_translate("MainWindow", "Save and Exit"))
        self.actionGo_to_next_Unaccounted.setText(_translate("MainWindow", "Go to next Unaccounted"))

